lva_events:
    resource: "@LVAEventsBundle/Resources/config/routing.yml"
    prefix:   /

lva_user:
    resource: "@LVAUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"